version: '3.7'
services:
  myapp:
    image: containous/whoami:latest
    deploy:
      replicas: 2
      labels:
        - envoy.endpoint.port=80
        - envoy.route.domain=nstapelbroek.com
        - envoy.route.path=/api
    networks:
      - edge-traffic

networks:
  edge-traffic:
    external: true