version: '3.7'
services:
  #  control-plane:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #      target: App

  envoy:
    image: envoyproxy/envoy:v1.15-latest
#    image: envoyproxy/envoy-dev:latest
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    environment:
      - ENVOY_UID=0 # need this since we'll bind on port 80
    ports:
      - 19000:19000
      - 443:443
      - 80:80
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - default
      - edge-traffic

networks:
  default:
  edge-traffic:
    external: true
