version: '3.7'
services:
  myapp:
    image: nstapelbroek/static-webserver:3
    deploy:
      replicas: 3
      labels:
        - envoy.endpoint.protocol=tcp # default, other option: udp
        - envoy.endpoint.port=80 # required, only one port per service atm though
        - envoy.route.domain=nstapelbroek.com # required
        - envoy.route.extra-domains=nstapelbroek.nl,www.nstapelbroek.nl,www.nstapelbroek.com # optional
        - envoy.route.path=/ # default
    networks:
      - default
      - edge-traffic

networks:
  default:
  edge-traffic:
    external: true