version: '3.7'
services:
  myapp:
    image: containous/whoami:latest
    deploy:
      replicas: 2
      labels:
        - envoy.endpoint.protocol=tcp # default, other option: udp
        - envoy.endpoint.port=80 # required, only one port per service atm though
        - envoy.route.domains=nstapelbroek.com # not implemented yet
        - envoy.route.path=/api # not implemented yet
    networks:
      - edge-traffic

networks:
  edge-traffic:
    external: true