version: '3.7'
services:
  myapp:
    image: containous/whoami:latest
    deploy:
      replicas: 2
      labels:
        - envoy.endpoint.port=80
    networks:
      - edge-traffic

networks:
  edge-traffic:
    external: true