version: '3.7'
services:
  myapp:
    image: nstapelbroek/static-webserver:3
    deploy:
      replicas: 3
      labels:
        - envoy.endpoint.protocol=tcp # default, other option: udp
        - envoy.endpoint.port=80 # required, only one port per service atm though
        - envoy.route.domain=nstapelbroek.com # not implemented yet
        - envoy.route.path=/api # not implemented yet
    ports:
      - 80
    networks:
      - default
      - edge-traffic

networks:
  default:
  edge-traffic:
    external: true