version: '3.7'

services:
  ci:
    image: nstapelbroek/upstream-service-demo:latest
    deploy:
      replicas: 2
      labels:
        - envoy.endpoint.port=8080
        - envoy.endpoint.timeout=30m
        - envoy.route.domain=mysite.com
        - envoy.route.path=/
    networks:
        - edge-traffic

networks:
  edge-traffic:
    external: true
