version: '3.7'

services:
  control-plane:
    image: nstapelbroek/envoy-swarm-control-plane:0.1
    command:
      - --ingress-network
      - edge-traffic
      - --storage-dir
      - /etc/ssl/certs/
      - --acme-email
      - replaceme@example.com
      # - --acme-accept-terms
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        window: 10s
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  proxy:
    image: nstapelbroek/envoy-swarm-edge:0.1
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.edge == true
      restart_policy:
        condition: any
        window: 10s
    networks:
      - default
      - edge-traffic
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host


networks:
  default: {}
  edge-traffic:
    external: true