version: '3.7'
services:
  control-plane:
    image: nstapelbroek/envoy-swarm-control-plane:0.15
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        window: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --debug
      - --storage-dir
      - /tmp/

  lb:
    image: nstapelbroek/envoy-edge:0.15
    deploy:
      placement:
        constraints:
          - node.labels.edge == true
        preferences:
          - spread: node.name
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - default
      - edge-traffic


networks:
  edge-traffic:
    external: true