overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
    - name: "envoy.resource_monitors.fixed_heap"
      typed_config:
        "@type": type.googleapis.com/envoy.config.resource_monitor.fixed_heap.v2alpha.FixedHeapConfig
        max_heap_size_bytes: 512000000 # 512MB
  actions:
    - name: "envoy.overload_actions.shrink_heap"
      triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.95
    - name: "envoy.overload_actions.stop_accepting_requests"
      triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.98

admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000

dynamic_resources:
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: control_plane

  cds_config:
    ads: {}
    resource_api_version: V3

  lds_config:
    ads: {}
    resource_api_version: V3

node:
  cluster: local-development
  id: test-id

static_resources:
  clusters:
    - name: control_plane
      type: strict_dns
      connect_timeout: 5s
      http2_protocol_options: {}
      load_assignment:
        cluster_name: control_plane
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: docker.host.internal
                      port_value: 9876

    - name: control_plane_acme
      type: strict_dns
      connect_timeout: 5s
      load_assignment:
        cluster_name: control_plane_acme
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: docker.host.internal
                      port_value: 8080
